### ISSUE TITLE
Tasks aus Küchendiskussion vom 19.3.2017

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#118]
![img_20170319_175358](https://cloud.githubusercontent.com/assets/776715/24083993/46a86966-0ce2-11e7-875b-255040d8e0ad.jpg)

- 30 cm höhe unter allen Elementen am Boden ausser Spülmaschine und Waschmaschine
- Ivar-Teile aus Getränkelager zusammenmontieren für neue Snackbar (Schräge Fächer für mehr Stauraum und mehr Sichtbarkeit)
- Spüle ersetzen für ein breiteres Becken und ohne Trockenbereich (ist eh nur Müllhalde)
- Herd ersetzen durch Kochplatten ohne Backofen
- Ofen kaufen und unter Mikrowelle einbauen auf Arbeitshöhe
- Statt dreckigem, unsortiertem Gewürzbord: Hängeschränke für Geschirr und seltener genutzte Gewürze in einen Hängeschrank. Häufiger genutzte Gewürze an einen besser erreichbaren Standort
- Vorratsdosen von IKEA (oder irgendwelche Anderen solange die tatsächlich Mottensicher sind)

Optional:

- Thekenbereich höhere Platte
- Bodenerneuerung

Aus dem Meeting vom 20. Aug2017:

- [x] #144 Ataris in Textillager wegräumen
- [x] #145 Getränkelager entrümpeln
- [x] #146 Textillager komplett leeren
- [ ] #147 Tardis umsetzen
- [ ] #148 Küchenumbau

**Comment by uwap** [comment]
> niedrigen Pizzaofen als Ersatz für Ofen kaufen und unter Mikrowelle einbauen auf Arbeitshöhe

Ich konnte leider nicht dabei sein, aber das finde ich doch jetzt schon ziemlich doof. Pizza ist immerhin nicht das einzige, was im RaumZeitLabor gebacken wird. Nach welchen Kriterien habt ihr euch denn gegen einen Ofen entschieden?

**Comment by Don42** [comment]
Haben wir nicht. @Bfritz0815 hat nicht alles mitbekommen.
Herd und Ofen werden getrennt. Ofen auf Höhe der Arbeitsplatte, aber in normaler Größe.
Die Unterschränke sollen aber niedrigere Höhe mit 30cm Füßen zum drunter putzen bekommen.

**Comment by uwap** [comment]
Ah. Das klingt sehr sinnvoll. Danke fürs aufklären!

**Comment by Bfritz0815** [comment]
Aus dem Meeting von Heute (20. Aug2017):

- [ ] #144 Ataris in Textillager wegräumen
- [ ] #145 Getränkelager entrümpeln
- [ ] #146 Textillager komplett leeren
- [ ] #147 Tardis umsetzen
- [ ] #148 Küchenumbau

**Comment by uwap** [comment]
Küchenumbau ist im gange. Tardis wird nicht umgesetzt. Ich schließe das issue. Alles weiter in #148
