### ISSUE TITLE
W&D 15. Oktober 2017

### ISSUE THREAD

**Issue by uwap** [raumzeitlabor/rzl-tuwat#154]
Tasks für den 2. Wipe and Defrag im Oktober:

**Hochregallager**
- [ ] Umsortierung Hochregallager. Ältere Projekte nach oben, Mitgliederkisten nach unten
- [ ] Altes RZL Zeug aus dem Hochregallager aussortieren*

**Getränkelager**
- [x] Altes RZL Zeug aus dem Getränkelager aussortieren* (#145)
- [x] Zeug Thematisch ordnen (Eine Ecke für MRMCD Zeug, eine Ecke für Team Retro Zeug, eine Ecke für Textilien ...) (#145)
- [ ] Zigarettenautomat: Mail auf Mailingliste (#149)
- [x] Team Retro Zeug aussortieren (#144)
- [x] Kiste von Moemoe in den Hauptraum -> Public (#142)

**Küche**
- [x] Die leere Küchenzeile abreißen, falls bis dahin der Vorstandsbriefkasten schon umgesetzt ist (#148)
- [x] Küchenschubladen neu Labeln
- [x] Alte Gewürze aussortieren (#120)
- [ ] Ofen Reinigen

**Olymp**
- [ ] Kram aussortieren*
- [ ] Zeug aufräumen

---

**Hauptraum**
- [x] Durchfegen
- [ ] Tische Abwischen

**Müll**
- [ ] Olymp -> Hauptraum
- [ ] Workshopraum -> Hauptraum
- [x] Rausbringen

\* Bevor Jemand meckert: Aussortieren heißt natürlich Mail auf die ML, zeug ins Lost & Found...
