### ISSUE TITLE
Zukunft des Sandstrahl-Kabinetts

### ISSUE THREAD

**Issue by Bfritz0815** [raumzeitlabor/rzl-tuwat#47]
# Aspects

1. Lange nicht benutzt
2. Gesundheitsrisiko durch den Staub und unsachgemäßen Umgang mit dem Reststaub (Wegsaugen anyone?)
3. unzureichender Atemschutz für Bediener und andere Anwesende i.d. Werkstatt (ihr glaubt doch nicht, dass die wenigen ollen Gebrauchtmasken irgendwsa bringen, oder?)
4. Platz kann sinnvoller für Anderes genutzt werden (Bandschleifer o.Ä.)
5. Sand dafür liegt auch  ungebraucht im Getränkelager rum

# Todo

- [x] kabinett abbauen  
- [ ] Sandstrahl-Kabinett mit Zubehör ins Getränkelager schaffen
- [ ] Frage klären: Wollen wir den noch behalten?
- [ ] Frage klären: Was ist mit dem Kompressor/Drucktank?

**Comment by abrock** [comment]
Ich benutze das Ding regelmäßig, "lange nicht benutzt" ist also falsch. Wegen dem Staub werde ich mal versuchen den Abluftfilter zu reinigen / ersetzen. Ich bin für behalten.

Den Kompressor benutze ich für das Sandstrahlkabinett und regelmäßig zum Reinigen der Stickmaschine.

**Comment by steeph-k** [comment]
Der Kompressor wird außerdem gelegentlich zum Reinigen von Laptop-Tastaturen benutzt, wofür er ja auch genau das richtige Format hat.

**Comment by Bfritz0815** [comment]
Wg Sandstrahler ist hier im Raum die Überegung aufgekommen, man könne den ja ggf. im Getränkelager unterbringen und nur bei Bedarf hervorholen. 
Ich würde da ggf sogar noch weiter gehen: Warum nciht das Ding mitsamt Kompressor im Getränkelager parken. 
Nach Ausbau und Entrümpeln des Raums und Ausbauen der 2. Etage sollte da reichlich Platz sein. 

Was die etlichen weiteren Anwendungen des Kompressors betrifft:
Soweit ich mich erinnere, hat der Raum eine wiederbefüllbare Druckkartusche gekauft als der Kompressor angeschafft wurde. 
Für diverse sauberpust-Aufgaben tuts die auch. Sollte der Bedarf an Luft so groß werden, dass eine Kartusche nicht mehr reicht, können wir ja weitere/größere kaufen. 


Ich weiss: Never change a running System. 
Aber dieses Running System ist derzeit am running out of space. 
Meine Reaktion: 
1. eine issue aufmachen mit Ideen und Diskussion für die Werkstatt (siehe https://github.com/raumzeitlabor/rzl-tuwat/issues/50 )
2. Also sofern wir nicht was tun um mehr Platz in der Werkstatt zu schaffen, werde ich vorerst auf Plenen gegen die Anschaffung weiterer Werkstatt Devices stimmen.

**Comment by Bfritz0815** [comment]
@abrock Not sure ob das mit dem Transportieren der Quarzsandschleuder quer durch 3 Teilräume so ne tolle Idee wäre. 

Frage: was treibst du mit der Stickmaschine, dass eine Dose (unspezifischer Größe) nicht mehr reicht? :)
lass mal demnächst darüber reden. Vielleicht fällt uns ja noch was dazu ein. Es geht ja auch hier nicht um "SOFORT!!!1!!!11!!!1" sondern eher mittel- bis langfristig.

**Comment by abrock** [comment]
So eine Stickmaschine hat einen Haufen Teile, die regelmäßig voller Fussel und Fadenreste sind: Umlaufgreifer, Messer, 15 Füße etc., wenn man die gründlich säubern will muss man aus verschiedenen Winkeln draufhalten, und so eine Druckflasche ist ziemlich klein.

Außerdem ist die Düse der Flasche deutlich kleiner als die des Kompressors, und bei der Stickmaschine geht es weniger darum ein bischen Staub aufzuwirbeln, eher darum das Öl in dem der Staub klebt wegzublasen, das geht mit der großen Düse besser.

**Comment by Bfritz0815** [comment]
Im wiki-Artikel zum Sandstrahler https://wiki.raumzeitlabor.de/wiki/Sandstrahlkabine  steht: 

> Die Sandstrahlkabine hat einen Anschluß für einen Staubsauger, um im Inneren der Kabine einen leichten Unterdruck zu produzieren. Leider ist unser Staubsauger zu kraftvoll für die Kabine - hier sollte demnächst mal ein einfacher, regelbarer Staubsauger beschafft werden.

Hat schon jemand nen passenden Staubsauger im Auge?

**Comment by s1lvester** [comment]
> Hat schon jemand nen passenden Staubsauger im Auge?

funktioniert bestimmt auch mit unserem Kärcher in der Werkstatt. Analog zum Saugadapt0r für die Kreissäge könnte man hier einfach(tm) einen "leaky" Adapt0r bauen.

**Comment by Bfritz0815** [comment]
Bei Gespräch darüber hat sich folgende Vorstellung ergeben: 

Ein Adapter für den Kärcher wäre sinnvoll. Der soll dann aber auch gleich folgende Dinge tun:

1. Einen neben-lufteilnlass haben, mit dem man den Unterdruck regulieren kann. (Bei vorigen Versuchen hat sich gezeigt, dass der Sauger soviel Unterdruck erzeugt, dass die Bedienung unpraktisch wird)
2. Einen Vorfilter o.Ä. bieten damit der Kärcher nicht den ganzen Quarzstaub abbekommt. (Wir erinnern uns: der wird ggf. gerne mal ohne Beutel betrieben. Dann hätten wir Quarzsand in der Mechanik)

**Comment by s1lvester** [comment]
Das wäre eigentlich was für mr. 3d-Printer Ingo.

Zum Thema "Vorfilter": Eigentlich ist der schon integriert (Innenseite Sandstrahlkabinett). Der funktioniert auch. Aus der Öffnung kommt mehr oder weniger nur feiner Staub.

**Comment by s1lvester** [comment]
Nachdem ich jetzt mehrfach beim Werkstatt aufräumen von Quarzsand Staub genervt war und DaFo gestern 20min den Staubsauger gefixt hat weil irgendwie ein Horst meinte den ganzen Sand damit aufsaugen zu müssen bin ich jetzt auch dafür das Ding raus zu werfen.

**Comment by Bfritz0815** [comment]
Sandstrahler hat jetzt ein Label, man solle den Sand nicht mehr per Staubsauger entfernen. Was auch immer das dann hilft...
